### ISSUE TITLE
Plugin doesn't work with PlayFramework 2.6.25

### ISSUE THREAD

**Issue by vladislav-tsarev-napier** [sbt/sbt-javaagent#27]
build.sbt
```
name := """play-scala-starter-example"""

version := "1.0-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayScala, JavaAgent)

resolvers += Resolver.sonatypeRepo("snapshots")

scalaVersion := "2.12.12"
javaAgents += "io.opentelemetry.javaagent" % "opentelemetry-javaagent" % "1.29.0" % "runtime"

libraryDependencies += guice
libraryDependencies += "org.scalatestplus.play" %% "scalatestplus-play" % "3.1.2" % Test
libraryDependencies += "com.h2database" % "h2" % "1.4.197"

fork in run := true
```
plugins.sbt
```
addSbtPlugin("com.github.sbt" % "sbt-javaagent" % "0.1.7")
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.6.25")
```
javaAgents are not added on
`sbt run`

If `PlayScala` removed from plugins, JavaAgent start to work.

**Comment by mkurz** [comment]
I don't think you will get any support for Play 2.6. Best to upgrade to latest Play version and try again.

**Comment by pvlugter** [comment]
The special reloading `run` from the sbt plugin for Play does not support forking, so the run java options, where the java agent option is added, are ignored.

We did add a forked reloading run for Play many years ago, but that's long since removed.

To run with the agent use `sbt runProd` instead, which will be forked and can have the agent attached. This is without the automatic dev reloading, and running in prod mode. 

Or if there's a better approach for newer versions of Play, @mkurz will know.

**Comment by srolel** [comment]
@vladislav-tsarev-napier were you able to get this working?
